//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/Scripts/InputSystem/PlayersInputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/InputSystem/PlayersInputMap.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayersInputMap: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayersInputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayersInputMap"",
    ""maps"": [
        {
            ""name"": ""Player1Move"",
            ""id"": ""2a7db825-d0b2-4f2a-b1d6-e0acc4a7a319"",
            ""actions"": [
                {
                    ""name"": ""MoveInputOne"",
                    ""type"": ""Value"",
                    ""id"": ""01f684e2-3a81-4f0d-a104-0d02fff954d6"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ActionInputOne"",
                    ""type"": ""Button"",
                    ""id"": ""94e0f2a6-eaa4-4a25-8666-9f2b619e66d5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeCamLeft"",
                    ""type"": ""Button"",
                    ""id"": ""3838a966-135f-4a5d-8bbb-da515a5e22a4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeCamRight"",
                    ""type"": ""Button"",
                    ""id"": ""0013c44a-da7f-45a8-ac7e-d473212e9eab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""60b805c7-a2ea-43f2-9b0d-17dcd852ea65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""820ac937-b1a1-4495-932b-2660ef82df20"",
                    ""path"": ""3DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""d96e962b-bed8-4492-b788-1c23597bfcfd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""e9876f37-5732-4fb1-817f-ed8571fac1c4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""291b7a63-3900-493b-9b04-54363ebdf5cf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""92d20c54-d02f-48ba-a89a-796f9ead175d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""7dbea21c-3b05-45be-8c95-18fcf7c69fee"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""b4312bdb-79c7-407d-830d-2f0378392276"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""493daf9b-f7aa-4b5f-a70c-8385ce12f25f"",
                    ""path"": ""3DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""8c639017-3376-49dc-ae7a-068a39d6aeaf"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""3422171c-aa12-4dd5-9fc6-ed1a1e621581"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""3a26c023-41c9-42f4-bd15-edabe54e8afc"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""5f501920-4cb2-4e9c-9a29-ff295bbe77d9"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""8f7a9a2b-ee25-4a90-ba7b-c5d8521c218f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""fc826b4b-c526-48d0-88ff-ef12bccb9abb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""42ea2c2b-3387-4357-b83c-1a3098fcf87e"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd7804f7-d79b-4f00-9028-a21325c78893"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionInputOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3d9b5a3-e648-42b5-bfac-7b1deb69a51a"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCamLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35151bd2-72b6-435b-9617-498aef4ab244"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCamLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35f8326d-1035-4de8-b1c3-fb7f4bec3b63"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCamRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9dd8812-c9e1-44fe-98a7-6fff1f02a7eb"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCamRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da5cbbc5-0d52-4b77-8b96-2a5e3e3af7b7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player2Move"",
            ""id"": ""42ad252d-9f22-4616-a64d-47dcafee263c"",
            ""actions"": [
                {
                    ""name"": ""MoveInputTwo"",
                    ""type"": ""Value"",
                    ""id"": ""7e704e03-cc5b-4ccc-8662-84af1d2f49dd"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ActionInputTwo"",
                    ""type"": ""Button"",
                    ""id"": ""d904301f-7bf8-48b0-a6c1-61bc78bf4971"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""ce660c9b-346a-4723-98d8-b7212246267e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Direconals"",
                    ""id"": ""61e0718b-b404-422d-b4df-4f1aea69e2b3"",
                    ""path"": ""3DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""08039552-a174-473b-aa98-8a69f97e8469"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""2d9f7b7b-f4d1-4c84-ba67-fa2f1e53e564"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""fe75a210-4163-4e6d-8973-534b7c5298cc"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""13163d23-b9d9-4026-8dd2-d6af5c8ec273"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""736eb174-2ae7-4a84-8e52-95ce711bb656"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""43d9f6b2-723e-4cd4-8d60-e573f5e5ccc5"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""8176a7e7-af85-4f1a-b82a-aac31b5c18a9"",
                    ""path"": ""3DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""ce917df5-eb5b-48de-8248-6d2ac4a912fa"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""cfd086c8-a7e7-476b-9737-b0e2260763d2"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""beb3ea78-10eb-4463-9618-fd471cbe24f7"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""fadcab38-e41b-46b6-af3c-1e404af0eefd"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Forward"",
                    ""id"": ""1a5b43f1-4340-4d21-bd48-9344e8188f50"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Backward"",
                    ""id"": ""c731563f-2e5e-40aa-988b-d31009fee384"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""68af8c6f-3173-4e93-8d0e-a0e517947883"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionInputTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d750bc5-d125-4d04-b5ae-79525352ea1b"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI Inputs"",
            ""id"": ""c54e27f8-16d5-4604-9f47-f9971d3e9449"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""321f2365-fc4f-4df6-b4b3-542f84bb047d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2de23ff5-c859-4f1c-bbe3-c4cd055b9097"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player1Move
        m_Player1Move = asset.FindActionMap("Player1Move", throwIfNotFound: true);
        m_Player1Move_MoveInputOne = m_Player1Move.FindAction("MoveInputOne", throwIfNotFound: true);
        m_Player1Move_ActionInputOne = m_Player1Move.FindAction("ActionInputOne", throwIfNotFound: true);
        m_Player1Move_ChangeCamLeft = m_Player1Move.FindAction("ChangeCamLeft", throwIfNotFound: true);
        m_Player1Move_ChangeCamRight = m_Player1Move.FindAction("ChangeCamRight", throwIfNotFound: true);
        m_Player1Move_Pause = m_Player1Move.FindAction("Pause", throwIfNotFound: true);
        // Player2Move
        m_Player2Move = asset.FindActionMap("Player2Move", throwIfNotFound: true);
        m_Player2Move_MoveInputTwo = m_Player2Move.FindAction("MoveInputTwo", throwIfNotFound: true);
        m_Player2Move_ActionInputTwo = m_Player2Move.FindAction("ActionInputTwo", throwIfNotFound: true);
        m_Player2Move_Mouse = m_Player2Move.FindAction("Mouse", throwIfNotFound: true);
        // UI Inputs
        m_UIInputs = asset.FindActionMap("UI Inputs", throwIfNotFound: true);
        m_UIInputs_Close = m_UIInputs.FindAction("Close", throwIfNotFound: true);
    }

    ~@PlayersInputMap()
    {
        UnityEngine.Debug.Assert(!m_Player1Move.enabled, "This will cause a leak and performance issues, PlayersInputMap.Player1Move.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Player2Move.enabled, "This will cause a leak and performance issues, PlayersInputMap.Player2Move.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UIInputs.enabled, "This will cause a leak and performance issues, PlayersInputMap.UIInputs.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player1Move
    private readonly InputActionMap m_Player1Move;
    private List<IPlayer1MoveActions> m_Player1MoveActionsCallbackInterfaces = new List<IPlayer1MoveActions>();
    private readonly InputAction m_Player1Move_MoveInputOne;
    private readonly InputAction m_Player1Move_ActionInputOne;
    private readonly InputAction m_Player1Move_ChangeCamLeft;
    private readonly InputAction m_Player1Move_ChangeCamRight;
    private readonly InputAction m_Player1Move_Pause;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player1Move".
    /// </summary>
    public struct Player1MoveActions
    {
        private @PlayersInputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Player1MoveActions(@PlayersInputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player1Move/MoveInputOne".
        /// </summary>
        public InputAction @MoveInputOne => m_Wrapper.m_Player1Move_MoveInputOne;
        /// <summary>
        /// Provides access to the underlying input action "Player1Move/ActionInputOne".
        /// </summary>
        public InputAction @ActionInputOne => m_Wrapper.m_Player1Move_ActionInputOne;
        /// <summary>
        /// Provides access to the underlying input action "Player1Move/ChangeCamLeft".
        /// </summary>
        public InputAction @ChangeCamLeft => m_Wrapper.m_Player1Move_ChangeCamLeft;
        /// <summary>
        /// Provides access to the underlying input action "Player1Move/ChangeCamRight".
        /// </summary>
        public InputAction @ChangeCamRight => m_Wrapper.m_Player1Move_ChangeCamRight;
        /// <summary>
        /// Provides access to the underlying input action "Player1Move/Pause".
        /// </summary>
        public InputAction @Pause => m_Wrapper.m_Player1Move_Pause;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player1Move; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Player1MoveActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Player1MoveActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Player1MoveActions" />
        public void AddCallbacks(IPlayer1MoveActions instance)
        {
            if (instance == null || m_Wrapper.m_Player1MoveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player1MoveActionsCallbackInterfaces.Add(instance);
            @MoveInputOne.started += instance.OnMoveInputOne;
            @MoveInputOne.performed += instance.OnMoveInputOne;
            @MoveInputOne.canceled += instance.OnMoveInputOne;
            @ActionInputOne.started += instance.OnActionInputOne;
            @ActionInputOne.performed += instance.OnActionInputOne;
            @ActionInputOne.canceled += instance.OnActionInputOne;
            @ChangeCamLeft.started += instance.OnChangeCamLeft;
            @ChangeCamLeft.performed += instance.OnChangeCamLeft;
            @ChangeCamLeft.canceled += instance.OnChangeCamLeft;
            @ChangeCamRight.started += instance.OnChangeCamRight;
            @ChangeCamRight.performed += instance.OnChangeCamRight;
            @ChangeCamRight.canceled += instance.OnChangeCamRight;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Player1MoveActions" />
        private void UnregisterCallbacks(IPlayer1MoveActions instance)
        {
            @MoveInputOne.started -= instance.OnMoveInputOne;
            @MoveInputOne.performed -= instance.OnMoveInputOne;
            @MoveInputOne.canceled -= instance.OnMoveInputOne;
            @ActionInputOne.started -= instance.OnActionInputOne;
            @ActionInputOne.performed -= instance.OnActionInputOne;
            @ActionInputOne.canceled -= instance.OnActionInputOne;
            @ChangeCamLeft.started -= instance.OnChangeCamLeft;
            @ChangeCamLeft.performed -= instance.OnChangeCamLeft;
            @ChangeCamLeft.canceled -= instance.OnChangeCamLeft;
            @ChangeCamRight.started -= instance.OnChangeCamRight;
            @ChangeCamRight.performed -= instance.OnChangeCamRight;
            @ChangeCamRight.canceled -= instance.OnChangeCamRight;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Player1MoveActions.UnregisterCallbacks(IPlayer1MoveActions)" />.
        /// </summary>
        /// <seealso cref="Player1MoveActions.UnregisterCallbacks(IPlayer1MoveActions)" />
        public void RemoveCallbacks(IPlayer1MoveActions instance)
        {
            if (m_Wrapper.m_Player1MoveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Player1MoveActions.AddCallbacks(IPlayer1MoveActions)" />
        /// <seealso cref="Player1MoveActions.RemoveCallbacks(IPlayer1MoveActions)" />
        /// <seealso cref="Player1MoveActions.UnregisterCallbacks(IPlayer1MoveActions)" />
        public void SetCallbacks(IPlayer1MoveActions instance)
        {
            foreach (var item in m_Wrapper.m_Player1MoveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player1MoveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Player1MoveActions" /> instance referencing this action map.
    /// </summary>
    public Player1MoveActions @Player1Move => new Player1MoveActions(this);

    // Player2Move
    private readonly InputActionMap m_Player2Move;
    private List<IPlayer2MoveActions> m_Player2MoveActionsCallbackInterfaces = new List<IPlayer2MoveActions>();
    private readonly InputAction m_Player2Move_MoveInputTwo;
    private readonly InputAction m_Player2Move_ActionInputTwo;
    private readonly InputAction m_Player2Move_Mouse;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player2Move".
    /// </summary>
    public struct Player2MoveActions
    {
        private @PlayersInputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Player2MoveActions(@PlayersInputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player2Move/MoveInputTwo".
        /// </summary>
        public InputAction @MoveInputTwo => m_Wrapper.m_Player2Move_MoveInputTwo;
        /// <summary>
        /// Provides access to the underlying input action "Player2Move/ActionInputTwo".
        /// </summary>
        public InputAction @ActionInputTwo => m_Wrapper.m_Player2Move_ActionInputTwo;
        /// <summary>
        /// Provides access to the underlying input action "Player2Move/Mouse".
        /// </summary>
        public InputAction @Mouse => m_Wrapper.m_Player2Move_Mouse;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player2Move; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Player2MoveActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Player2MoveActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Player2MoveActions" />
        public void AddCallbacks(IPlayer2MoveActions instance)
        {
            if (instance == null || m_Wrapper.m_Player2MoveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player2MoveActionsCallbackInterfaces.Add(instance);
            @MoveInputTwo.started += instance.OnMoveInputTwo;
            @MoveInputTwo.performed += instance.OnMoveInputTwo;
            @MoveInputTwo.canceled += instance.OnMoveInputTwo;
            @ActionInputTwo.started += instance.OnActionInputTwo;
            @ActionInputTwo.performed += instance.OnActionInputTwo;
            @ActionInputTwo.canceled += instance.OnActionInputTwo;
            @Mouse.started += instance.OnMouse;
            @Mouse.performed += instance.OnMouse;
            @Mouse.canceled += instance.OnMouse;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Player2MoveActions" />
        private void UnregisterCallbacks(IPlayer2MoveActions instance)
        {
            @MoveInputTwo.started -= instance.OnMoveInputTwo;
            @MoveInputTwo.performed -= instance.OnMoveInputTwo;
            @MoveInputTwo.canceled -= instance.OnMoveInputTwo;
            @ActionInputTwo.started -= instance.OnActionInputTwo;
            @ActionInputTwo.performed -= instance.OnActionInputTwo;
            @ActionInputTwo.canceled -= instance.OnActionInputTwo;
            @Mouse.started -= instance.OnMouse;
            @Mouse.performed -= instance.OnMouse;
            @Mouse.canceled -= instance.OnMouse;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Player2MoveActions.UnregisterCallbacks(IPlayer2MoveActions)" />.
        /// </summary>
        /// <seealso cref="Player2MoveActions.UnregisterCallbacks(IPlayer2MoveActions)" />
        public void RemoveCallbacks(IPlayer2MoveActions instance)
        {
            if (m_Wrapper.m_Player2MoveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Player2MoveActions.AddCallbacks(IPlayer2MoveActions)" />
        /// <seealso cref="Player2MoveActions.RemoveCallbacks(IPlayer2MoveActions)" />
        /// <seealso cref="Player2MoveActions.UnregisterCallbacks(IPlayer2MoveActions)" />
        public void SetCallbacks(IPlayer2MoveActions instance)
        {
            foreach (var item in m_Wrapper.m_Player2MoveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player2MoveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Player2MoveActions" /> instance referencing this action map.
    /// </summary>
    public Player2MoveActions @Player2Move => new Player2MoveActions(this);

    // UI Inputs
    private readonly InputActionMap m_UIInputs;
    private List<IUIInputsActions> m_UIInputsActionsCallbackInterfaces = new List<IUIInputsActions>();
    private readonly InputAction m_UIInputs_Close;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI Inputs".
    /// </summary>
    public struct UIInputsActions
    {
        private @PlayersInputMap m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UIInputsActions(@PlayersInputMap wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UIInputs/Close".
        /// </summary>
        public InputAction @Close => m_Wrapper.m_UIInputs_Close;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UIInputs; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UIInputsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UIInputsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UIInputsActions" />
        public void AddCallbacks(IUIInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_UIInputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIInputsActionsCallbackInterfaces.Add(instance);
            @Close.started += instance.OnClose;
            @Close.performed += instance.OnClose;
            @Close.canceled += instance.OnClose;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UIInputsActions" />
        private void UnregisterCallbacks(IUIInputsActions instance)
        {
            @Close.started -= instance.OnClose;
            @Close.performed -= instance.OnClose;
            @Close.canceled -= instance.OnClose;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UIInputsActions.UnregisterCallbacks(IUIInputsActions)" />.
        /// </summary>
        /// <seealso cref="UIInputsActions.UnregisterCallbacks(IUIInputsActions)" />
        public void RemoveCallbacks(IUIInputsActions instance)
        {
            if (m_Wrapper.m_UIInputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UIInputsActions.AddCallbacks(IUIInputsActions)" />
        /// <seealso cref="UIInputsActions.RemoveCallbacks(IUIInputsActions)" />
        /// <seealso cref="UIInputsActions.UnregisterCallbacks(IUIInputsActions)" />
        public void SetCallbacks(IUIInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_UIInputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIInputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UIInputsActions" /> instance referencing this action map.
    /// </summary>
    public UIInputsActions @UIInputs => new UIInputsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player1Move" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Player1MoveActions.AddCallbacks(IPlayer1MoveActions)" />
    /// <seealso cref="Player1MoveActions.RemoveCallbacks(IPlayer1MoveActions)" />
    public interface IPlayer1MoveActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveInputOne" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveInputOne(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionInputOne" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionInputOne(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChangeCamLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChangeCamLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ChangeCamRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnChangeCamRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPause(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player2Move" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Player2MoveActions.AddCallbacks(IPlayer2MoveActions)" />
    /// <seealso cref="Player2MoveActions.RemoveCallbacks(IPlayer2MoveActions)" />
    public interface IPlayer2MoveActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveInputTwo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveInputTwo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ActionInputTwo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnActionInputTwo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mouse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouse(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI Inputs" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UIInputsActions.AddCallbacks(IUIInputsActions)" />
    /// <seealso cref="UIInputsActions.RemoveCallbacks(IUIInputsActions)" />
    public interface IUIInputsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Close" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClose(InputAction.CallbackContext context);
    }
}
